steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'PORT=$_PORT'
      - '--build-arg'
      - 'DATABASE_URL=$_DATABASE_URL'
      - '--build-arg'
      - 'FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - '--build-arg'
      - 'FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'FIREBASE_APP_ID=$_FIREBASE_APP_ID'
      - '--build-arg'
      - 'SERVICE_ACCOUNT_KEY=$_SERVICE_ACCOUNT_KEY'
      - '--build-arg'
      - 'STORAGE_BUCKET_NAME=$_STORAGE_BUCKET_NAME'
      - '--build-arg'
      - 'OPEN_API_KEY=$_OPEN_API_KEY'
      - '--build-arg'
      - 'GOOGLE_CLOUD_KEY=$_GOOGLE_CLOUD_KEY'
      - '--build-arg'
      - 'GOOGLE_CALENDAR_TOKEN=$_GOOGLE_CALENDAR_TOKEN'
      - '--build-arg'
      - 'GOOGLE_CALENDAR_CREDENTIALS=$_GOOGLE_CALENDAR_CREDENTIALS'
      - '--build-arg'
      - 'ML_API=$_ML_API'
      - '-t'
      - 'gcr.io/dicoding-mp/mentoring-platform-api'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dicoding-mp/mentoring-platform-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mentoring-platform-api'
      - '--image'
      - 'gcr.io/dicoding-mp/mentoring-platform-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--project'
      - 'dicoding-mp'
options:
  logging: CLOUD_LOGGING_ONLY
