steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dicoding-mp/mentoring-platform-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dicoding-mp/mentoring-platform-api']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mentoring-platform-api'
      - '--image'
      - 'gcr.io/dicoding-mp/mentoring-platform-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--project'
      - 'dicoding-mp'
    env:
      - 'DATABASE_URL=_DATABASE_URL'
      - 'FIREBASE_API_KEY=_FIREBASE_API_KEY'
      - 'FIREBASE_AUTH_DOMAIN=_FIREBASE_AUTH_DOMAIN'
      - 'FIREBASE_PROJECT_ID=_FIREBASE_PROJECT_ID'
      - 'FIREBASE_STORAGE_BUCKET=_FIREBASE_STORAGE_BUCKET'
      - 'FIREBASE_MESSAGING_SENDER_ID=_FIREBASE_MESSAGING_SENDER_ID'
      - 'FIREBASE_APP_ID=_FIREBASE_APP_ID'
      - 'SERVICE_ACCOUNT_KEY=_SERVICE_ACCOUNT_KEY'
      - 'STORAGE_BUCKET_NAME=_STORAGE_BUCKET_NAME'
      - 'PORT=_PORT'
      - 'OPEN_API_KEY=_OPEN_API_KEY'
      - 'GOOGLE_CLOUD_KEY=_GOOGLE_CLOUD_KEY'
      - 'GOOGLE_CALENDAR_TOKEN=_GOOGLE_CALENDAR_TOKEN'
      - 'GOOGLE_CALENDAR_CREDENTIALS=_GOOGLE_CALENDAR_CREDENTIALS'
      - 'ML_API=_ML_API'
options:
  logging: CLOUD_LOGGING_ONLY
