FROM node:lts-alpine

ARG PORT
ARG DATABASE_URL
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID
ARG FIREBASE_APP_ID
ARG SERVICE_ACCOUNT_KEY
ARG STORAGE_BUCKET_NAME
ARG OPEN_API_KEY
ARG GOOGLE_CLOUD_KEY
ARG GOOGLE_CALENDAR_TOKEN
ARG GOOGLE_CALENDAR_CREDENTIALS
ARG ML_API

ENV PORT=$PORT
ENV DATABASE_URL=$DATABASE_URL
ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_APP_ID=$FIREBASE_APP_ID
ENV SERVICE_ACCOUNT_KEY=$SERVICE_ACCOUNT_KEY
ENV STORAGE_BUCKET_NAME=$STORAGE_BUCKET_NAME
ENV OPEN_API_KEY=$OPEN_API_KEY
ENV GOOGLE_CLOUD_KEY=$GOOGLE_CLOUD_KEY
ENV GOOGLE_CALENDAR_TOKEN=$GOOGLE_CALENDAR_TOKEN
ENV GOOGLE_CALENDAR_CREDENTIALS=$GOOGLE_CALENDAR_CREDENTIALS
ENV ML_API=$ML_API

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# If you are building your code for production
# RUN npm ci --only=production

COPY . .

EXPOSE 8080 

RUN npx prisma generate
RUN npm run build

CMD [ "node", "dist/src/index.js" ]